project = guess
objs = $(project).o
CC=gcc
CFLAGS := $(CFLAGS) -Wall
.PHONY: all
all: $(project)
$(project): $(objs)
all: $(project)
.PHONY: clean
clean:
			rm -f $(project)
			rm -f *.o

                    
